[package]
name = "isthat-ong"
version = "0.1.0"
edition = "2021"
description = "A simple ong system" # github copilot suggested me this. :)
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = "0.19"
